### ISSUE TITLE
Add support for Baubles Expanded

### ISSUE THREAD

**Issue by Omgise** [repletsin5/AdventureBackpack#1]
I want Adventure Backpacks to go right in the baubles slot

**Comment by repletsin5** [comment]
Which slot would it go in?

**Comment by repletsin5** [comment]
I see that the baubles api is already included in this mod. Doesnt seem to be used tho

**Comment by Omgise** [comment]
> Which slot would it go in?

Can you customize a backpack slot?

**Comment by Omgise** [comment]
See https://github.com/jss2a98aj/Baubles-Expanded/issues/7 , Perhaps AdventureBackpack has to have support added on its end.

**Comment by repletsin5** [comment]
Sorry for taking a while to respond. If this would require me making some assets e.g. for the slot image, i think thats out of what i am willing to for this mod, as i am not good at asset creation.

**Comment by Omgise** [comment]
Okay, I understand
